spring:
  datasource:
    url: jdbc:mysql://localhost/lstock?useunicode=true&characterencoding=utf-8
    username: lstock
    password: 13t0ck
    driverClassName: com.mysql.jdbc.Driver

  jpa:
      database: MYSQL
      show-sql: false
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL5Dialect
        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
  view:
    prefix: /WEB-INF/jsp/
    suffix: .jsp